#--------displaying message from playbook play
#- name: demo on playbook
#  hosts: all
#  tasks:
#  - name: task1
#    ansible.builtin.debug:
#      msg: Hello from Playbook play
#----------(i)Pre-defined variable from user(hardcoded)
#- name: demo of var from user hardcoded
#  hosts: all
#  vars:
#    URL: www.example.com
#    a: 1000
#  tasks:
#    - name: print var at task1
#      ansible.builtin.debug:
#        msg: URL = {{URL}}
#    - name: print var at task2
#      ansible.builtin.debug:
#        msg: a = {{a}}, {{URL}}
#----------(ii)variables from a file
#- name: accessing var from file
#  hosts: all
#  vars_files:
#    - sample-vars.yml
#  tasks:
#    - name: printing var from file
#      ansible.builtin.debug:
#        msg: "{{URL}}"
#----------(iii)Task level variable
#- name: Demo on Task level variable
#  hosts: all
#  tasks:
#    - name: printing task1 variable
#      ansible.builtin.debug:
#        msg: "{{URL1}}"
#      vars:
#        URL1: www.example.come
#    - name: Printing task2 variable
#      ansible.builtin.debug:
#        msg: "{{URL2}}"
#      vars:
#        URL2: www.example2.com
#-----------(iv)Inventory level variable
- name: Demo on Inventory Level variable
  hosts: all
  tasks:
    - name: task accessing inv var
      ansible.builtin.debug:
        msg: "{{URL}}"
#-------------(v)command line variables
- name: Demo on Command Line Variables
  hosts: all
  tasks:
    - name: task with command line var
      ansible.builtin.debug:
        msg: "{{URL}}"